'use client';

import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    welcome: 'Welcome to Krishi Sahayak',
    subtitle: 'Your trusted farming companion',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    email: 'Email',
    phone: 'Phone Number',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    name: 'Full Name',
    village: 'Village/City',
    state: 'State',
    cropType: 'Main Crop Type',
    forgotPassword: 'Forgot Password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    signInWith: 'Sign in with',
    or: 'or',
    createAccount: 'Create Account',
    login: 'Login',
    selectLanguage: 'Select Language',
    agriculture: 'Agriculture',
    farming: 'Farming',
    crops: 'Crops',
    weather: 'Weather',
    market: 'Market',
    help: 'Help',
    selectLandArea: 'Select Your Land Area',
    landAreaDescription: 'Draw a polygon on the map to mark your farming area',
    areaSelected: 'Area Selected',
    area: 'Area',
    center: 'Center',
    country: 'Country',
    coordinates: 'Coordinates',
    continue: 'Continue',
    back: 'Back',
    skip: 'Skip for Now',
    dashboard: 'Dashboard',
    insights: 'Insights',
    recommendations: 'Recommendations',
    orders: 'Orders',
    landAnalysis: 'Land Analysis',
    cropRecommendations: 'Crop Recommendations',
    aiInsights: 'AI Insights',
    productRecommendations: 'Product Recommendations',
    orderHistory: 'Order History',
    orderNow: 'Order Now',
    quantity: 'Quantity',
    priority: 'Priority',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    total: 'Total',
    status: 'Status',
    completed: 'Completed',
    pending: 'Pending',
    cancelled: 'Cancelled',
    noOrders: 'No orders yet. Check out our recommendations!',
    welcome: 'Welcome',
    logout: 'Logout',
    loading: 'Loading...',
    tryAgain: 'Try Again',
    orderPlaced: 'Order placed successfully!',
    orderFailed: 'Failed to place order. Please try again.',
    errorPlacingOrder: 'Error placing order. Please try again.',
    failedToLoad: 'Failed to load dashboard data. Please try again.',
    processing: 'Processing...',
    landAnalysisInsights: 'Land Analysis & Insights',
    aiPoweredAnalysis: 'AI-powered analysis of your agricultural land',
    landDetails: 'Land Details',
    weatherConditions: 'Weather Conditions',
    soilCropHealth: 'Soil & Crop Health',
    temperature: 'Temperature',
    humidity: 'Humidity',
    weather: 'Weather',
    windSpeed: 'Wind Speed',
    rainChance: 'Rain Chance',
    ndvi: 'NDVI',
    uvIndex: 'UV Index',
    location: 'Location',
    recommendationScore: 'Recommendation Score',
    whyThisCrop: 'Why this crop?',
    benefits: 'Benefits',
    season: 'Season',
    water: 'Water',
    yield: 'Yield',
    price: 'Price',
    totalPrice: 'Total Price',
    automatedOrderingResults: 'Automated Ordering Results',
    automatedOrderingCompleted: 'Automated ordering completed',
    error: 'Error',
    viewRecommendations: 'View Recommendations',
    noOrdersYet: 'No orders yet',
    startByChecking: 'Start by checking out our personalized recommendations!',
    orderNumber: 'Order #',
    orderedVia: 'Ordered via Krishi Sahayak'
  },
  hi: {
    welcome: 'कृषि सहायक में आपका स्वागत है',
    subtitle: 'आपका भरोसेमंद कृषि साथी',
    signIn: 'साइन इन करें',
    signUp: 'साइन अप करें',
    email: 'ईमेल',
    phone: 'फोन नंबर',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    name: 'पूरा नाम',
    village: 'गाँव/शहर',
    state: 'राज्य',
    cropType: 'मुख्य फसल का प्रकार',
    forgotPassword: 'पासवर्ड भूल गए?',
    dontHaveAccount: 'खाता नहीं है?',
    alreadyHaveAccount: 'पहले से खाता है?',
    signInWith: 'के साथ साइन इन करें',
    or: 'या',
    createAccount: 'खाता बनाएं',
    login: 'लॉगिन',
    selectLanguage: 'भाषा चुनें',
    agriculture: 'कृषि',
    farming: 'खेती',
    crops: 'फसलें',
    weather: 'मौसम',
    market: 'बाजार',
    help: 'सहायता',
    selectLandArea: 'अपना भूमि क्षेत्र चुनें',
    landAreaDescription: 'अपने खेती के क्षेत्र को चिह्नित करने के लिए मानचित्र पर एक बहुभुज बनाएं',
    areaSelected: 'क्षेत्र चुना गया',
    area: 'क्षेत्र',
    center: 'केंद्र',
    country: 'देश',
    coordinates: 'निर्देशांक',
    continue: 'जारी रखें',
    back: 'वापस',
    skip: 'अभी छोड़ें',
    dashboard: 'डैशबोर्ड',
    insights: 'अंतर्दृष्टि',
    recommendations: 'सुझाव',
    orders: 'ऑर्डर',
    landAnalysis: 'भूमि विश्लेषण',
    cropRecommendations: 'फसल सुझाव',
    aiInsights: 'AI अंतर्दृष्टि',
    productRecommendations: 'उत्पाद सुझाव',
    orderHistory: 'ऑर्डर इतिहास',
    orderNow: 'अभी ऑर्डर करें',
    quantity: 'मात्रा',
    priority: 'प्राथमिकता',
    high: 'उच्च',
    medium: 'मध्यम',
    low: 'कम',
    total: 'कुल',
    status: 'स्थिति',
    completed: 'पूर्ण',
    pending: 'लंबित',
    cancelled: 'रद्द',
    noOrders: 'अभी तक कोई ऑर्डर नहीं। हमारे सुझाव देखें!',
    welcome: 'स्वागत',
    logout: 'लॉगआउट',
    loading: 'लोड हो रहा है...',
    tryAgain: 'फिर से कोशिश करें',
    orderPlaced: 'ऑर्डर सफलतापूर्वक दिया गया!',
    orderFailed: 'ऑर्डर देने में विफल। कृपया फिर से कोशिश करें।',
    errorPlacingOrder: 'ऑर्डर देने में त्रुटि। कृपया फिर से कोशिश करें।',
    failedToLoad: 'डैशबोर्ड डेटा लोड करने में विफल। कृपया फिर से कोशिश करें।',
    processing: 'प्रसंस्करण...',
    landAnalysisInsights: 'भूमि विश्लेषण और अंतर्दृष्टि',
    aiPoweredAnalysis: 'आपकी कृषि भूमि का AI-संचालित विश्लेषण',
    landDetails: 'भूमि विवरण',
    weatherConditions: 'मौसम की स्थिति',
    soilCropHealth: 'मिट्टी और फसल स्वास्थ्य',
    temperature: 'तापमान',
    humidity: 'आर्द्रता',
    weather: 'मौसम',
    windSpeed: 'हवा की गति',
    rainChance: 'बारिश की संभावना',
    ndvi: 'NDVI',
    uvIndex: 'UV सूचकांक',
    location: 'स्थान',
    recommendationScore: 'सुझाव स्कोर',
    whyThisCrop: 'यह फसल क्यों?',
    benefits: 'लाभ',
    season: 'मौसम',
    water: 'पानी',
    yield: 'उपज',
    price: 'मूल्य',
    totalPrice: 'कुल मूल्य',
    automatedOrderingResults: 'स्वचालित ऑर्डरिंग परिणाम',
    automatedOrderingCompleted: 'स्वचालित ऑर्डरिंग पूर्ण',
    error: 'त्रुटि',
    viewRecommendations: 'सुझाव देखें',
    noOrdersYet: 'अभी तक कोई ऑर्डर नहीं',
    startByChecking: 'हमारे व्यक्तिगत सुझाव देखकर शुरू करें!',
    orderNumber: 'ऑर्डर #',
    orderedVia: 'कृषि सहायक के माध्यम से ऑर्डर किया गया'
  },
  pa: {
    welcome: 'ਕ੍ਰਿਸ਼ੀ ਸਹਾਇਕ ਵਿੱਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ',
    subtitle: 'ਤੁਹਾਡਾ ਭਰੋਸੇਮੰਦ ਖੇਤੀ ਸਾਥੀ',
    signIn: 'ਸਾਈਨ ਇਨ ਕਰੋ',
    signUp: 'ਸਾਈਨ ਅੱਪ ਕਰੋ',
    email: 'ਈਮੇਲ',
    phone: 'ਫੋਨ ਨੰਬਰ',
    password: 'ਪਾਸਵਰਡ',
    confirmPassword: 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    name: 'ਪੂਰਾ ਨਾਮ',
    village: 'ਪਿੰਡ/ਸ਼ਹਿਰ',
    state: 'ਰਾਜ',
    cropType: 'ਮੁੱਖ ਫਸਲ ਦਾ ਪ੍ਰਕਾਰ',
    forgotPassword: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
    dontHaveAccount: 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
    alreadyHaveAccount: 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?',
    signInWith: 'ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ',
    or: 'ਜਾਂ',
    createAccount: 'ਖਾਤਾ ਬਣਾਓ',
    login: 'ਲੌਗਿਨ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    agriculture: 'ਕ੍ਰਿਸ਼ੀ',
    farming: 'ਖੇਤੀ',
    crops: 'ਫਸਲਾਂ',
    weather: 'ਮੌਸਮ',
    market: 'ਬਾਜ਼ਾਰ',
    help: 'ਸਹਾਇਤਾ',
    selectLandArea: 'ਆਪਣਾ ਜ਼ਮੀਨ ਦਾ ਖੇਤਰ ਚੁਣੋ',
    landAreaDescription: "ਆਪਣੇ ਖੇਤੀ ਦੇ ਖੇਤਰ ਨੂੰ ਚਿੰਨ੍ਹਿਤ ਕਰਨ ਲਈ ਨਕਸ਼ੇ ਤੇ ਇੱਕ ਬਹੁਭੁਜ ਬਣਾਓ",
    areaSelected: 'ਖੇਤਰ ਚੁਣਿਆ ਗਿਆ',
    area: 'ਖੇਤਰ',
    center: 'ਕੇਂਦਰ',
    country: 'ਦੇਸ਼',
    coordinates: 'ਗੁਣਕ',
    continue: 'ਜਾਰੀ ਰੱਖੋ',
    back: 'ਵਾਪਸ',
    skip: 'ਹੁਣੇ ਛੱਡੋ'
  },
  kn: {
    welcome: 'ಕೃಷಿ ಸಹಾಯಕಕ್ಕೆ ಸ್ವಾಗತ',
    subtitle: 'ನಿಮ್ಮ ನಂಬಿಕೆಯ ಕೃಷಿ ಸಹಚರ',
    signIn: 'ಸೈನ್ ಇನ್ ಮಾಡಿ',
    signUp: 'ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    email: 'ಇಮೇಲ್',
    phone: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    password: 'ಪಾಸ್ವರ್ಡ್',
    confirmPassword: 'ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    name: 'ಪೂರ್ಣ ಹೆಸರು',
    village: 'ಗ್ರಾಮ/ನಗರ',
    state: 'ರಾಜ್ಯ',
    cropType: 'ಮುಖ್ಯ ಬೆಳೆ ಪ್ರಕಾರ',
    forgotPassword: 'ಪಾಸ್ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?',
    dontHaveAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    alreadyHaveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    signInWith: 'ಜೊತೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    or: 'ಅಥವಾ',
    createAccount: 'ಖಾತೆ ರಚಿಸಿ',
    login: 'ಲಾಗಿನ್',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    agriculture: 'ಕೃಷಿ',
    farming: 'ವ್ಯವಸಾಯ',
    crops: 'ಬೆಳೆಗಳು',
    weather: 'ಹವಾಮಾನ',
    market: 'ಮಾರುಕಟ್ಟೆ',
    help: 'ಸಹಾಯ',
    selectLandArea: 'ನಿಮ್ಮ ಭೂಮಿ ಪ್ರದೇಶವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    landAreaDescription: 'ನಿಮ್ಮ ಕೃಷಿ ಪ್ರದೇಶವನ್ನು ಗುರುತಿಸಲು ನಕ್ಷೆಯಲ್ಲಿ ಬಹುಭುಜವನ್ನು ಬರೆಯಿರಿ',
    areaSelected: 'ಪ್ರದೇಶ ಆಯ್ಕೆಮಾಡಲಾಗಿದೆ',
    area: 'ಪ್ರದೇಶ',
    center: 'ಕೇಂದ್ರ',
    country: 'ದೇಶ',
    coordinates: 'ನಿರ್ದೇಶಾಂಕಗಳು',
    continue: 'ಮುಂದುವರಿಸಿ',
    back: 'ಹಿಂದಕ್ಕೆ',
    skip: 'ಇದೀಗ ಬಿಟ್ಟುಬಿಡಿ'
  },
  ta: {
    welcome: 'கிரிஷி சஹாயகுக்கு வரவேற்கிறோம்',
    subtitle: 'உங்கள் நம்பகமான விவசாய துணை',
    signIn: 'உள்நுழைய',
    signUp: 'பதிவு செய்ய',
    email: 'மின்னஞ்சல்',
    phone: 'தொலைபேசி எண்',
    password: 'கடவுச்சொல்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    name: 'முழு பெயர்',
    village: 'கிராமம்/நகரம்',
    state: 'மாநிலம்',
    cropType: 'முக்கிய பயிர் வகை',
    forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
    dontHaveAccount: 'கணக்கு இல்லையா?',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    signInWith: 'உடன் உள்நுழைய',
    or: 'அல்லது',
    createAccount: 'கணக்கு உருவாக்க',
    login: 'உள்நுழைவு',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    agriculture: 'விவசாயம்',
    farming: 'வேளாண்மை',
    crops: 'பயிர்கள்',
    weather: 'வானிலை',
    market: 'சந்தை',
    help: 'உதவி',
    selectLandArea: 'உங்கள் நில பகுதியைத் தேர்ந்தெடுக்கவும்',
    landAreaDescription: 'உங்கள் விவசாய பகுதியைக் குறிக்க வரைபடத்தில் பலகோணம் வரையவும்',
    areaSelected: 'பகுதி தேர்ந்தெடுக்கப்பட்டது',
    area: 'பகுதி',
    center: 'மையம்',
    country: 'நாடு',
    coordinates: 'ஆயங்கள்',
    continue: 'தொடரவும்',
    back: 'திரும்பவும்',
    skip: 'இப்போது தவிர்க்கவும்'
  },
  te: {
    welcome: 'కృషి సహాయక్కు స్వాగతం',
    subtitle: 'మీ విశ్వసనీయ వ్యవసాయ సహచరుడు',
    signIn: 'సైన్ ఇన్ చేయండి',
    signUp: 'సైన్ అప్ చేయండి',
    email: 'ఇమెయిల్',
    phone: 'ఫోన్ నంబర్',
    password: 'పాస్వర్డ్',
    confirmPassword: 'పాస్వర్డ్ ని నిర్ధారించండి',
    name: 'పూర్తి పేరు',
    village: 'గ్రామం/నగరం',
    state: 'రాష్ట్రం',
    cropType: 'ప్రధాన పంట రకం',
    forgotPassword: 'పాస్వర్డ్ మర్చిపోయారా?',
    dontHaveAccount: 'ఖాతా లేదా?',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    signInWith: 'తో సైన్ ఇన్ చేయండి',
    or: 'లేదా',
    createAccount: 'ఖాతా సృష్టించండి',
    login: 'లాగిన్',
    selectLanguage: 'భాషను ఎంచుకోండి',
    agriculture: 'వ్యవసాయం',
    farming: 'వ్యవసాయ',
    crops: 'పంటలు',
    weather: 'వాతావరణం',
    market: 'మార్కెట్',
    help: 'సహాయం',
    selectLandArea: 'మీ భూమి ప్రాంతాన్ని ఎంచుకోండి',
    landAreaDescription: 'మీ వ్యవసాయ ప్రాంతాన్ని గుర్తించడానికి మ్యాప్‌లో బహుభుజి గీయండి',
    areaSelected: 'ప్రాంతం ఎంచుకోబడింది',
    area: 'ప్రాంతం',
    center: 'కేంద్రం',
    country: 'దేశం',
    coordinates: 'కోఆర్డినేట్లు',
    continue: 'కొనసాగించు',
    back: 'వెనుకకు',
    skip: 'ఇప్పుడు దాటవేయి'
  },
  bn: {
    welcome: 'কৃষি সহায়কে স্বাগতম',
    subtitle: 'আপনার বিশ্বস্ত কৃষি সঙ্গী',
    signIn: 'সাইন ইন করুন',
    signUp: 'সাইন আপ করুন',
    email: 'ইমেইল',
    phone: 'ফোন নম্বর',
    password: 'পাসওয়ার্ড',
    confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
    name: 'পুরো নাম',
    village: 'গ্রাম/শহর',
    state: 'রাজ্য',
    cropType: 'প্রধান ফসলের ধরন',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    dontHaveAccount: 'অ্যাকাউন্ট নেই?',
    alreadyHaveAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    signInWith: 'দিয়ে সাইন ইন করুন',
    or: 'অথবা',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    login: 'লগইন',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    agriculture: 'কৃষি',
    farming: 'চাষাবাদ',
    crops: 'ফসল',
    weather: 'আবহাওয়া',
    market: 'বাজার',
    help: 'সাহায্য',
    selectLandArea: 'আপনার জমির এলাকা নির্বাচন করুন',
    landAreaDescription: 'আপনার চাষের এলাকা চিহ্নিত করতে মানচিত্রে একটি বহুভুজ আঁকুন',
    areaSelected: 'এলাকা নির্বাচিত হয়েছে',
    area: 'এলাকা',
    center: 'কেন্দ্র',
    country: 'দেশ',
    coordinates: 'স্থানাঙ্ক',
    continue: 'চালিয়ে যান',
    back: 'ফিরে যান',
    skip: 'এখনই এড়িয়ে যান'
  },
  gu: {
    welcome: 'કૃષિ સહાયકમાં આપનું સ્વાગત છે',
    subtitle: 'તમારો વિશ્વસનીય કૃષિ સાથી',
    signIn: 'સાઇન ઇન કરો',
    signUp: 'સાઇન અપ કરો',
    email: 'ઇમેઇલ',
    phone: 'ફોન નંબર',
    password: 'પાસવર્ડ',
    confirmPassword: 'પાસવર્ડની પુષ્ટિ કરો',
    name: 'પૂર્ણ નામ',
    village: 'ગામ/શહેર',
    state: 'રાજ્ય',
    cropType: 'મુખ્ય પાકનો પ્રકાર',
    forgotPassword: 'પાસવર્ડ ભૂલી ગયા?',
    dontHaveAccount: 'ખાતું નથી?',
    alreadyHaveAccount: 'પહેલેથી ખાતું છે?',
    signInWith: 'સાથે સાઇન ઇન કરો',
    or: 'અથવા',
    createAccount: 'ખાતું બનાવો',
    login: 'લોગિન',
    selectLanguage: 'ભાષા પસંદ કરો',
    agriculture: 'કૃષિ',
    farming: 'ખેતી',
    crops: 'પાક',
    weather: 'હવામાન',
    market: 'બજાર',
    help: 'મદદ',
    selectLandArea: 'તમારો જમીનનો વિસ્તાર પસંદ કરો',
    landAreaDescription: 'તમારા ખેતીના વિસ્તારને ચિહ્નિત કરવા માટે નકશા પર બહુભુજ દોરો',
    areaSelected: 'વિસ્તાર પસંદ કર્યો',
    area: 'વિસ્તાર',
    center: 'કેન્દ્ર',
    country: 'દેશ',
    coordinates: 'કોઓર્ડિનેટ્સ',
    continue: 'ચાલુ રાખો',
    back: 'પાછા',
    skip: 'હમણાં છોડો'
  },
  mr: {
    welcome: 'कृषी सहायक मध्ये आपले स्वागत आहे',
    subtitle: 'आपला विश्वासू शेती साथी',
    signIn: 'साइन इन करा',
    signUp: 'साइन अप करा',
    email: 'ईमेल',
    phone: 'फोन नंबर',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्डची पुष्टी करा',
    name: 'पूर्ण नाव',
    village: 'गाव/शहर',
    state: 'राज्य',
    cropType: 'मुख्य पिकाचा प्रकार',
    forgotPassword: 'पासवर्ड विसरलात?',
    dontHaveAccount: 'खाते नाही?',
    alreadyHaveAccount: 'आधीपासून खाते आहे?',
    signInWith: 'सह साइन इन करा',
    or: 'किंवा',
    createAccount: 'खाते तयार करा',
    login: 'लॉगिन',
    selectLanguage: 'भाषा निवडा',
    agriculture: 'कृषी',
    farming: 'शेती',
    crops: 'पिके',
    weather: 'हवामान',
    market: 'बाजार',
    help: 'मदत',
    selectLandArea: 'तुमचा जमिनीचा भाग निवडा',
    landAreaDescription: 'तुमच्या शेतीच्या भागाला चिन्हांकित करण्यासाठी नकाशावर बहुभुज काढा',
    areaSelected: 'भाग निवडला',
    area: 'भाग',
    center: 'केंद्र',
    country: 'देश',
    coordinates: 'निर्देशांक',
    continue: 'सुरू ठेवा',
    back: 'मागे',
    skip: 'आत्ता वगळा'
  }
};

const languages = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'kn', name: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ta', name: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
  { code: 'bn', name: 'বাংলা', flag: '🇮🇳' },
  { code: 'gu', name: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'mr', name: 'मराठी', flag: '🇮🇳' }
];

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('en');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Check for saved language preference (only in browser)
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('krishi-sahayak-language');
      if (savedLanguage && translations[savedLanguage]) {
        setCurrentLanguage(savedLanguage);
      }
    }
    setIsLoading(false);
  }, []);

  const changeLanguage = (languageCode) => {
    setCurrentLanguage(languageCode);
    if (typeof window !== 'undefined') {
      localStorage.setItem('krishi-sahayak-language', languageCode);
    }
  };

  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key;
  };

  const value = {
    currentLanguage,
    changeLanguage,
    t,
    languages,
    isLoading
  };

  if (isLoading) {
    return <div className="flex items-center justify-center min-h-screen">Loading...</div>;
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
